-- lobs.nvim — WebSocket client for lobs-core
-- Connects via websocat. For CF Access servers, gets a token via
-- cloudflared and passes it as a cookie header.
local M = {}
M.__index = M

local protocol = require("lobs.protocol")
local auth = require("lobs.auth")
local sessions = require("lobs.sessions")

--- Create a new client
---@param config table
---@return table
function M.new(config)
  local self = setmetatable({}, M)
  self.config = config
  self.session_key = nil
  self._connected = false
  self._connecting = false
  self._ws_job = nil
  self._handlers = {}
  self._tool_executor = require("lobs.tools").new()
  self._reconnect_timer = nil
  self._reconnect_attempts = 0
  self._max_reconnect_attempts = 5
  self._outgoing_queue = {}
  self._intentional_disconnect = false
  self._cf_token = nil
  -- Session persistence
  self._resumed_session = false
  -- Response tracking for disconnect handling
  self._waiting_for_response = false
  self._last_data_time = nil
  self._stall_timer = nil
  -- History handler callback (registered by chat UI)
  self._history_handler = nil
  -- Session title (auto-generated by server)
  self._session_title = nil
  return self
end

--- Connect to lobs-core via WebSocket
---@param callback function|nil Called when connected (err)
function M:connect(callback)
  if self._connected then
    if callback then callback(nil) end
    return
  end
  if self._connecting then
    if callback then callback("already connecting") end
    return
  end

  self._connecting = true
  self._intentional_disconnect = false

  -- Try to resume an existing session for this project
  if not self.session_key then
    local project_root = require("lobs.context").get_project_root()
    local existing_key = sessions.get_session_for_project(project_root)
    if existing_key then
      self.session_key = existing_key
      self._resumed_session = true
    end
  end

  -- Get CF Access token (no-op if not using Cloudflare)
  auth.get_token(self.config, function(token, err)
    if err then
      self._connecting = false
      vim.notify("Lobs: " .. err, vim.log.levels.ERROR)
      if callback then callback(err) end
      return
    end
    self._cf_token = token
    self:_connect_ws(callback)
  end)
end

--- Internal: establish WebSocket connection (after auth)
---@param callback function|nil
function M:_connect_ws(callback)
  if vim.fn.executable("websocat") ~= 1 then
    self._connecting = false
    local err = "websocat not found. Install: brew install websocat"
    vim.notify("Lobs: " .. err, vim.log.levels.ERROR)
    if callback then callback(err) end
    return
  end

  local server = self.config.server or ""
  if server == "" then
    self._connecting = false
    local err = "No server URL configured"
    vim.notify("Lobs: " .. err, vim.log.levels.ERROR)
    if callback then callback(err) end
    return
  end

  local ws_url = server:gsub("/+$", "") .. "/api/vim/ws"

  -- Build websocat command
  -- NOTE: websocat's -H flag is greedy and eats subsequent args.
  -- Must use -H=value syntax or put -H last (before URL won't work).
  local cmd
  if self._cf_token then
    cmd = {
      "websocat", "--text",
      ws_url,
      "-H=Cookie: CF_Authorization=" .. self._cf_token,
    }
  else
    cmd = { "websocat", "--text", ws_url }
  end

  local buf = ""
  local got_message = false

  self._ws_job = vim.system(
    cmd,
    {
      text = true,
      stdin = true,
      stdout = function(_, data)
        if not data then return end
        vim.schedule(function()
          buf = buf .. data
          while true do
            local nl = buf:find("\n")
            if not nl then break end
            local line = buf:sub(1, nl - 1)
            buf = buf:sub(nl + 1)
            if line ~= "" then
              if not got_message then
                got_message = true
                self._connected = true
                self._connecting = false
                self._reconnect_attempts = 0
              end
              self:_on_message(line)
            end
          end
        end)
      end,
      stderr = function(_, data)
        if data and data ~= "" then
          vim.schedule(function()
            local trimmed = data:gsub("%s+$", "")
            if trimmed ~= "" and not self._connected then
              -- Check for auth-specific errors
              if trimmed:match("302") or trimmed:match("[Rr]edirect") then
                vim.notify("Lobs: Auth rejected — run :LobsAuth then :LobsConnect", vim.log.levels.ERROR)
              else
                vim.notify("Lobs WS: " .. trimmed, vim.log.levels.WARN)
              end
            end
          end)
        end
      end,
    },
    function(_result)
      vim.schedule(function()
        local was_connected = self._connected
        self._connected = false
        self._connecting = false
        self._ws_job = nil

        -- Stop stall timer on disconnect
        self:_stop_stall_timer()

        if self._intentional_disconnect then return end

        if not was_connected then
          -- Check stderr for auth issues
          local stderr = _result.stderr or ""
          if stderr:match("302") or stderr:match("[Rr]edirect") then
            vim.notify("Lobs: Auth expired — run :LobsAuth", vim.log.levels.WARN)
            return -- don't reconnect on auth failure
          end
        end

        -- If we were waiting for a response, show pending message
        if self._waiting_for_response then
          vim.notify("Lobs: Disconnected — response pending on server. Will resume on reconnect.", vim.log.levels.WARN)
          -- Notify handlers about the disconnect-while-waiting state
          if self._handlers.on_disconnect_pending then
            self._handlers.on_disconnect_pending()
          end
        end

        self:_on_disconnect()
      end)
    end
  )

  -- Build project context for new sessions (README, AGENTS.md, pwd, etc.)
  local ctx = require("lobs.context")
  local project_root = ctx.get_project_root()
  local project_context = nil
  if not self._resumed_session then
    project_context = ctx.build_project_context()
  end

  -- Send session.open immediately
  self:_send_raw(protocol.session_open({
    projectRoot = project_root,
    sessionKey = self.session_key,
    projectContext = project_context,
  }))

  if callback then callback(nil) end
end

--- Send a raw message (direct write, no queue)
---@param msg table
function M:_send_raw(msg)
  if not self._ws_job then return end
  local json_str = vim.fn.json_encode(msg) .. "\n"
  pcall(function() self._ws_job:write(json_str) end)
end

--- Send a message, queuing if not connected
---@param msg table
function M:_send(msg)
  if self._connected and self._ws_job then
    self:_send_raw(msg)
  else
    table.insert(self._outgoing_queue, msg)
  end
end

--- Stop any current stream
function M:stop_stream()
  self._handlers = {}
  self._waiting_for_response = false
  self:_stop_stall_timer()
end

--- Send a chat message
---@param content string
---@param context table
---@param handlers table
function M:send_message(content, context, handlers)
  self._handlers = handlers
  self._waiting_for_response = true
  self._last_data_time = os.time()
  self:_start_stall_timer()

  self:connect(function(err)
    if err then
      self._waiting_for_response = false
      self:_stop_stall_timer()
      if handlers.on_error then handlers.on_error(err) end
      return
    end

    self:_send(protocol.chat_send({
      sessionKey = self.session_key,
      content = content,
      context = context,
    }))
  end)
end

--- Register a handler for session history responses
---@param handler function(messages: table[])
function M:on_history(handler)
  self._history_handler = handler
end

--- Request session history from the server
function M:request_history()
  if self.session_key and self._connected then
    self:_send(protocol.session_history({
      sessionKey = self.session_key,
    }))
  end
end

--- Start a timer that fires if no data is received for 30s while streaming
function M:_start_stall_timer()
  self:_stop_stall_timer()
  self._stall_timer = vim.defer_fn(function()
    if self._waiting_for_response then
      self._last_data_time = self._last_data_time or os.time()
      local elapsed = os.time() - self._last_data_time
      if elapsed >= 30 and self._handlers.on_stall then
        self._handlers.on_stall(elapsed)
      end
      -- Re-arm the timer
      self:_start_stall_timer()
    end
  end, 30000)
end

--- Stop the stall timer
function M:_stop_stall_timer()
  if self._stall_timer then
    pcall(function()
      if type(self._stall_timer) == "userdata" then
        self._stall_timer:stop()
      end
    end)
    self._stall_timer = nil
  end
end

--- Handle an incoming WebSocket message
---@param raw string JSON string
function M:_on_message(raw)
  local ok, msg = pcall(vim.fn.json_decode, raw)
  if not ok or not msg or not msg.type then return end

  -- Update last data time for stall detection
  self._last_data_time = os.time()

  local t = msg.type

  if t == "session.opened" then
    local old_key = self.session_key
    self.session_key = msg.sessionKey
    self._session_title = msg.title

    -- Persist the session
    local project_root = require("lobs.context").get_project_root()
    sessions.save_session(msg.sessionKey, project_root, msg.title)

    if self._resumed_session and old_key == msg.sessionKey then
      vim.notify("Lobs: reconnected (session resumed)", vim.log.levels.INFO)
      -- Request history to populate the chat UI
      self:request_history()
    else
      vim.notify("Lobs: connected (new session)", vim.log.levels.INFO)
      self._resumed_session = false
    end

    -- Flush queued messages
    for _, queued in ipairs(self._outgoing_queue) do
      self:_send_raw(queued)
    end
    self._outgoing_queue = {}

  elseif t == "session.history" then
    -- Server responded with message history
    if self._history_handler and msg.messages then
      self._history_handler(msg.messages)
    end
    -- Update title if included in history response
    if msg.title and self.session_key then
      self._session_title = msg.title
      local project_root = require("lobs.context").get_project_root()
      sessions.save_session(self.session_key, project_root, msg.title)
      if self._handlers.on_title_update then
        self._handlers.on_title_update(msg.title)
      end
    end

  elseif t == "session.title" then
    -- Server generated/updated a session title
    if msg.title and self.session_key then
      self._session_title = msg.title
      local project_root = require("lobs.context").get_project_root()
      sessions.save_session(self.session_key, project_root, msg.title)
      if self._handlers.on_title_update then
        self._handlers.on_title_update(msg.title)
      end
    end

  elseif t == "chat.delta" then
    if self._handlers.on_text then
      self._handlers.on_text(msg.content or "")
    end

  elseif t == "chat.status" then
    local status = msg.status
    if status == "thinking" and self._handlers.on_thinking then
      self._handlers.on_thinking()
    elseif status == "tool_running" and self._handlers.on_tool_start then
      self._handlers.on_tool_start(msg.toolName, msg.toolInput)
    elseif status == "tool_done" and self._handlers.on_tool_result then
      self._handlers.on_tool_result(msg.toolName, msg.result, msg.isError)
    elseif status == "done" then
      self._waiting_for_response = false
      self:_stop_stall_timer()
      if self._handlers.on_done then
        self._handlers.on_done()
      end
    elseif status == "error" then
      self._waiting_for_response = false
      self:_stop_stall_timer()
      if self._handlers.on_error then
        self._handlers.on_error(msg.error or "unknown error")
      end
    elseif status == "queued" and self._handlers.on_thinking then
      self._handlers.on_thinking()
    end

  elseif t == "tool.request" then
    self:_handle_tool_request(msg)

  elseif t == "diff.propose" then
    self:_handle_diff_propose(msg)

  elseif t == "error" then
    local errmsg = msg.message or "server error"
    if self._handlers.on_error then
      self._handlers.on_error(errmsg)
    end
  end
end

--- Handle a tool execution request
---@param msg table
function M:_handle_tool_request(msg)
  local tool_name = msg.tool
  local tool_input = msg.args or msg.input or {}
  local request_id = msg.id
  local tool_use_id = msg.toolUseId

  -- Don't fire on_tool_start/on_tool_result here — the server sends
  -- chat.status events (tool_running/tool_done) which already handle
  -- UI updates. Firing both causes duplicate tool entries in the chat.

  self._tool_executor:execute(tool_name, tool_input, function(result, is_error)
    self:_send(protocol.tool_result({
      id = request_id,
      toolUseId = tool_use_id,
      content = result,
      isError = is_error or false,
    }))
  end)
end

--- Handle a diff proposal
---@param msg table
function M:_handle_diff_propose(msg)
  local diff = require("lobs.diff")
  diff.show_proposal(msg, function(accepted)
    self:_send(protocol.diff_resolve({
      diffId = msg.diffId,
      accepted = accepted,
    }))
  end)
end

--- Handle disconnection with exponential backoff
function M:_on_disconnect()
  if self._reconnect_attempts >= self._max_reconnect_attempts then
    vim.notify("Lobs: gave up reconnecting — :LobsConnect to retry", vim.log.levels.ERROR)
    self._reconnect_attempts = 0
    return
  end

  self._reconnect_attempts = self._reconnect_attempts + 1
  local delay = math.min(1000 * math.pow(2, self._reconnect_attempts - 1), 30000)

  vim.notify(string.format("Lobs: reconnecting in %ds...", math.floor(delay / 1000)), vim.log.levels.WARN)

  self._reconnect_timer = vim.defer_fn(function()
    self._reconnect_timer = nil
    self:connect()
  end, delay)
end

--- Disconnect
function M:disconnect()
  self._intentional_disconnect = true

  if self._reconnect_timer then
    pcall(function()
      if type(self._reconnect_timer) == "userdata" then
        self._reconnect_timer:stop()
      end
    end)
    self._reconnect_timer = nil
  end

  self:_stop_stall_timer()

  if self._ws_job then
    pcall(function() self._ws_job:kill("SIGTERM") end)
    self._ws_job = nil
  end

  self._connected = false
  self._connecting = false
  self._reconnect_attempts = 0
  self._waiting_for_response = false
  vim.notify("Lobs: disconnected", vim.log.levels.INFO)
end

--- Get connection status
function M:status()
  local state = "disconnected"
  if self._connected then
    state = "connected"
  elseif self._connecting then
    state = "connecting"
  end
  return {
    state = state,
    server = self.config.server,
    session = self.session_key,
    auth = self._cf_token and "authenticated" or "none",
    resumed = self._resumed_session,
    waiting = self._waiting_for_response,
  }
end

--- Reset session (starts a new session, clears project mapping)
function M:reset_session()
  -- Clear the project mapping so a new session is created
  local project_root = require("lobs.context").get_project_root()
  sessions.clear_project_mapping(project_root)

  self.session_key = nil
  self._resumed_session = false
  self._waiting_for_response = false
  self:_stop_stall_timer()

  self:_send(protocol.session_open({
    projectRoot = project_root,
  }))
end

return M
